### PR TITLE
Added requirements.txt

### PR DESCRIPTION
**Pull request by mdfaisal98**
This PR adds a requirements.txt file to the project, solving #5 .

### CODE REVIEW

**Review by RemDelaporteMathurin — CHANGES_REQUESTED** [review]
Thank you so much @mdfaisal98 ! This is appreciated.

Since this is your first PR on an open-source project, let me give you some advice:

- Reviewing a PR will be easy if some description is added. Here, it could simply be "This PR adds a requirements.txt file to the project, solving #5 ". A link to the issue you are solving allows reviewers to clearly identify what problem your fixing.
- Regarding the code, I think the file setup.py needs to be updated too.
It's missing a `install_requires` key (see this example: https://github.com/IRFM/divHretention/blob/702c4b58f1721917d665134b9bc85287cb002c23/setup.py#L1-L26)

**Comment by mdfaisal98** [comment]
Thank you for the advice @RemDelaporteMathurin . I have updated the PR as per requested.

**Comment by RemDelaporteMathurin** [comment]
This seems ok to me! Let's merge it!

@mdfaisal98 don't hesitate to leave a star if you like the package :-)

**Comment by mdfaisal98** [comment]
@RemDelaporteMathurin Thanks for helping me in my first open source contribution!

**Comment by Shimwell** [comment]
Sorry for getting here a bit late. Just wanted to mention as this code also requires openmc we can see that openmc request numpy version great than or equal to 1.9 ```numpy>=1.9```

https://github.com/openmc-dev/openmc/blob/eacd8f6bba414cac12f65059a3c17226fd0a201f/setup.py#L69

**Comment by RemDelaporteMathurin** [comment]
Oh did we miss the most important dependency? 😄 

@mdfaisal98 do you think you could be up to it?

@Shimwell do we  have an example somewhere regarding how to put openmc in the requirements?

**Comment by mdfaisal98** [comment]
So I just need to change the version of numpy from `1.21.2` to `>=1.9` ?

**Comment by RemDelaporteMathurin** [comment]
Yes that's it

**Comment by mdfaisal98** [comment]
@RemDelaporteMathurin I have made the changes.

**Pull request merged**
