### PR TITLE
removed Parameterized

### PR DESCRIPTION
**Pull request by shimwell**
This appears to fix the issue #80 that I noticed.

I think the CI runs with the current openmc release so this might need changing to the develop version

### CODE REVIEW

**Comment by RemDelaporteMathurin** [comment]
Not really sure what a metaclass is but looks like [it can be solved](https://stackoverflow.com/questions/11276037/resolving-metaclass-conflicts).

@pschriwise any idea why replacing `openmc.Source` by `openmc.IndependentSource` broke things?

**Comment by RemDelaporteMathurin** [comment]
> I believe it has to do with `SourceBase` inheriting from the abstract base class type (`ABC`). We added some abstract methods that are implemented in the derived classes related to XML exports.

Ok. Does that need we need to add a __metaclass__ argument to our derived classes?

**Comment by pshriwise** [comment]
> Ok. Does that need we need to add a **metaclass** argument to our derived classes?

I'm honestly not sure how to handle this. `Parameterized` inherits from Python's built-in `type` while `openmc.SourceBase` inherits from `ABC`. I'm not sure how to get a new class to resolve the order in which it should try to satisfy the new type definition for a class that inherits from both of these.

**Comment by shimwell** [comment]
closing in favor of #83

**Pull request closed without merging**
