### PR TITLE
Using openmc source plotter for plotting methods

### PR DESCRIPTION
**Pull request by shimwell**
This PR is a rework of #63 with feedback taken onboard.

The source class is now openmc.Source and it has been monkey patched to add the desired plotting methods.

This now just looks and behaves like a regular openmc source but it has a few plot methods

### CODE REVIEW

**Comment by shimwell** [comment]
tests are now passing here as well :tada:

**Review by RemDelaporteMathurin — COMMENTED** [review]
Hi

I don't see where openmc-source-plotter is used here. It seems to simply be imported.

Anyway, my idea in my previous comments (maybe I wasn't clear so happy to chat about it on the phone or smth) was that we agreed in #41 that openmc-source-plotter and openmc-plasma-source should remain seperate.

I think we have a choice to make (but more on the OSP side of things).
Either we have OSP as a complete standalone package and in that case the "old" OSP was very good at that since it used functions to plot sources without changing the source objects.
Or we integrate completely OSP in this package (but I understood why this isn't a good idea).

This current PR seems to be a weird mix of the two imo.

If the two packages are seperate, it should be the users responibility to use OSP to plot their sources and OSP wouldn't have to be a dependency of OPS at all.

Happy to discuss it further 😄

**Comment by shimwell** [comment]
The change is quite sneaky, by simply importing ```openmc_source_plotter``` the openmc.Source object gains plotting methods.

**Comment by RemDelaporteMathurin** [comment]
> The change is quite sneaky, by simply importing `openmc_source_plotter` the `openmc.Source` object gains plotting methods. This is done via a monkey patch

Ah ok. Not sure this is good practice haha

It is kinda confusing really... What motivated the move in OSP from functions to a class-based architecture?
I don't really see the benefits here. It's a mix between having things seperate, and having things bundled in the same package... confusing.

**Comment by shimwell** [comment]
No worries I can still use this package with the plotter by importing them both in the user script.

The user script for class based is a bit simpler than before IMO

function based
```python
import openmc
import openmc_source_plotter as osp
my_source = openmc.Source()
my_source.space = openmc.stats.Point((0, 0, 0))
my_source.angle = openmc.stats.Isotropic()
my_source.energy = openmc.stats.Discrete([14e6], [1])
osp.plot_source_energy(source=my_source)
```

class based
```python
import openmc
import openmc_source_plotter
my_source = openmc.Source()
my_source.space = openmc.stats.Point((0, 0, 0))
my_source.angle = openmc.stats.Isotropic()
my_source.energy = openmc.stats.Discrete([14e6], [1])
my_source.plot_source_energy()
```

**Comment by RemDelaporteMathurin** [comment]
> The user script for class based is a bit simpler than before IMO

It's not a lot simpler. It requires the users to understand the monkeypatch thing... it is not straightforward (my misunderstanding is a good example haha).

And it creates a discrepency with the openmc documentation...
I just don't know if it's worth the trouble.

I think I'd rather have the packages seperated than bundled like that.

**Comment by shimwell** [comment]
I shall close this PR, but to answer the documentation question I can make documentation in the package to describe the additional 4 methods added to openmc.Source

**Pull request closed without merging**
