### PR TITLE
Next openMC release

### PR DESCRIPTION
**Pull request by RemDelaporteMathurin**
This is an attempt at fixing #80

### CODE REVIEW

**Comment by RemDelaporteMathurin** [comment]
@shimwell fully removing  `param` stuff solves the failing tests in #172

However, the input checks are now fails but this is easy to fix.

**Comment by RemDelaporteMathurin** [comment]
@shimwell this is now ready for review.

In a nutshell, removed all `param` stuff and replaced with good old getters and setters methods.

**Comment by shimwell** [comment]
Thanks for maintaining this package Remi, the best part of this is the tokamak plasma source you made. Sadly I don't use this source much anymore but good to keep this package alive.

I shall review and perhaps we make a release after the next openmc release

**Comment by RemDelaporteMathurin** [comment]
> Thanks for maintaining this package Remi, the best part of this is the tokamak plasma source you made. Sadly I don't use this source much anymore but good to keep this package alive.
> 
> I shall review and perhaps we make a release after the next openmc release

No problem. Maybe we can wait until the next openmc release and ping to a static version of the openmc image instead of develop.

**Review by shimwell — APPROVED** [review]
Nice PR, many thanks

I plan to follow this up with a PR that modernizes the install method and another one that checks the version of openmc used is >= 0.13.4

**Comment by RemDelaporteMathurin** [comment]
Oh so we're merging this now? the newest version of openmc hasn't been released yet though

**Comment by shimwell** [comment]
Oh sorry, I thought that was the plan. We don't make a PyPi release till the openmc release

**Comment by egor1abs** [comment]
Hello! What about updating package for OpenMC 0.14.0?

**Comment by shimwell** [comment]
thanks @egor1abs I've just made a releae of version 0.3.0
[openmc-plasma-source ](https://pypi.org/project/openmc-plasma-source/0.3.0/)

**Pull request merged**
