### PR TITLE
Update to package configuration

### PR DESCRIPTION
**Pull request by LiamPattinson**
This update aims to bring openmc-plasma-source in line with PEP 517 recommendations for packaging etc. The build/install details in setup.py are moved to setup.cfg and pyproject.toml as simple input files. Rather than calling:

- `python setup.py install`/`python setup.py develop`
- `python setup.py sdist bdist_wheel`

One should instead call:

- `pip install .`/`pip install -e .` (for 'develop' mode)
- `python -m build`

Rather than using a requirements file, the project requirements may be listed in setup.cfg, and optional dependencies may be installed using:

- `pip install -e .[tests]` (-e is optional)

This update also introduces automatic version inference, meaning the git tag is the 'single source of truth' for versioning. The version is updated with developer tags when between patch versions, i.e. one commit after 0.5.3 will be 0.5.4.dev0+[git commit].d[date].

### CODE REVIEW

**Comment by shimwell** [comment]
Great to have this all in one place. Looking forward to making use of this elsewhere as well. @RemDelaporteMathurin we have a similar PR on the Paramak that has been merged already and I think this one is good to go if you are happy with it

**Comment by RemDelaporteMathurin** [comment]
@shimwell @LiamPattinson thanks again for this. For some reason the CI/ testing workflow failed, does it need updating too?

**Comment by LiamPattinson** [comment]
Going to be honest, I'm really not sure why that failed. It's odd that pytest ran fine, but the python calls didn't.  All I can think of is that circleci might be using Python 3 for pip calls, and Python 2.7 for direct python calls. I've made it explicit, and we'll see how it goes.

**Comment by LiamPattinson** [comment]
I had to play around in the openmc docker image to get to the root of this, and I think it might be as simple as doing a proper install rather than a 'develop' install in the CI. Calling `pip install -e .` in a locally hosted docker container led to similar issues of openmc-plasma-source not being included in the python path.

**Comment by RemDelaporteMathurin** [comment]
@LiamPattinson for some reason there seem to be some conflicts with this PR and I can't run the workflow until there are fixed

**Comment by LiamPattinson** [comment]
Sorry about that, the latest fix seems to have done it.

**Review by RemDelaporteMathurin — APPROVED** [review]
Thanks for this @LiamPattinson

**Pull request merged**
