### PR TITLE
Made TokamakSource automatic.

### PR DESCRIPTION
**Pull request by mdfaisal98**
This PR makes TokamakSource more automatic by defining it in the `__init__()` method, solving #13.

### CODE REVIEW

**Comment by RemDelaporteMathurin** [comment]
@mdfaisal98 thanks for working on this.
A few things:
- Could you please change the target branch to fusion-energy:develop
- Could you adapt the example script (in the example folder) to remove the calls of make_openmc_sources and sample_sources please?

**Comment by Shimwell** [comment]
Oh it looks like FusionRingSource now requires the argument radius and the test doesn't have that argument, this is somewhat unrelated to the aim of the PR.

**Comment by RemDelaporteMathurin** [comment]
> Oh it looks like FusionRingSource now requires the argument radius and the test doesn't have that argument, this is somewhat unrelated to the aim of the PR.

Ah yes it is related to #14 

@mdfaisal98 you need to update your main branch which doesn't have the latest changes

https://stefanbauer.me/articles/how-to-keep-your-git-fork-up-to-date

This link explains how to keep your forks up to date: this is essential when it comes to contributions

**Comment by Shimwell** [comment]
There is now a "fetch upstream" button on forks that can just be clicked. It is towards the upper right corner

**Comment by mdfaisal98** [comment]
I think the issue was due to the fact that I had made my changes in `mdfaisal98:main` which didn't have the test changes of the branch `develop`. Should I close this PR and create a new one? @RemDelaporteMathurin

**Comment by RemDelaporteMathurin** [comment]
@mdfaisal98 by fetching the upstream (syncing your fork with this repo) and then pushing the changes to your main, this PR should update automatically, no need to close it.

Although if you prefer to start fresh you can of course :-)

**Comment by RemDelaporteMathurin** [comment]
The tests seem to pass and this seems ready to merge!

Thanks @mdfaisal98 for this effort! 🎉

**Comment by mdfaisal98** [comment]
> @mdfaisal98 by fetching the upstream (syncing your fork with this repo) and then pushing the changes to your main, this PR should update automatically, no need to close it.
> 
> Although if you prefer to start fresh you can of course :-)

I have made changes. Thanks for the help @RemDelaporteMathurin @Shimwell

**Pull request merged**
